# fly.toml app configuration file generated for csharp-api on 2023-10-23T17:40:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "csharp-api"
primary_region = "lax"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
